### ISSUE TITLE
Class Notes

### ISSUE THREAD

**Issue by brianamarie** [githubteacher/essentials-aug#1]
Hello! 👋 

I will post notes throughout today and tomorrow to help keep everyone up to speed. If you have questions, feel free to ask them [in the Gitter chat room](https://gitter.im/githubteacher/essentials-aug). If you can't access that, feel free to comment in this thread. Be sure to include `@brianamarie` so I don't miss it!

**Comment by brianamarie** [comment]
## Day 1: Wednesday, August 10

Section 1/3

#### Getting Ready for Class
- Make sure you have a [github.com](https://github.com) account

#### Getting Started
- Git is a decentralized version control system. We read more about that [here](https://git-scm.com/book/en/v2/Getting-Started-Git-Basics)
- Make sure you have Git installed locally, version 1.9 or higher
  - Windows: [GitHub Desktop](https://desktop.github.com/)
  - Mac/Linux: [Git Scm](https://git-scm.com/)
- Check your Git version with `git --version`

#### Configure Git
- Git has three levels of configuration: `--system`, `--global`, and `--local`. We'll use `--global` today.
- Type the following configurations
  - `git config --global user.name "Your Actual Name"`
  - `git config --global user.email "youractual@email.com"`
  - Windows: `git config --global core.autocrlf true`
  - Mac/Linux: `git config --global core.autocrlf input`
  - Optional text editor:
    - If you have atom as a text editor: `git config --global core.editor "atom --wait"`
    - Get help with other text editors [here](https://help.github.com/articles/associating-text-editors-with-git/)
  - `git config --global push.default`

#### Working-locally.adoc
- CD into a place where you are comfortable creating a new file
- Create a new repository locally: `git init git-essentials`
- CD into your new repository: `cd git-essentials`
- View all files within the new repository 
  - Windows: `dir /a`
  - Mac/Linux: `ls -al`
- See your current file status with `git status`
- Create a new README file: `touch README.md`
- Add some material: `echo "This is some content" >> README.md`
- Verify what's in your readme: `cat README.md`
- See what's changed: `git status`
- Stage the file with `git add README.md`
- Commit the file with: `git commit`
  - If your text editor default is configured, your text editor will open and you can create your commit message there. Type your message, save, and close the editor.
  - If your defaults aren't configured, you may get an error. No worries! Type: `git commit -m "Enter commit message here"`

#### Git Flow
- We discuss the Git and GitHub workflow using [GitHub Guides](https://guides.github.com/introduction/flow/)
  - Branch
    - Create an exact copy of the project where you can work on a new feature that will later be merged in
    - It's good practice to make all commits on branches other than master
    - View current local branches: `git branch`
    - Create new branch: `git branch branch-name`
    - Move to that branch to work: `git checkout branch-name`
    - Open the README.md file on your branch, make and save changes
    - See state of files: `git status`
  - Two-Stage commit
    - Stage all files for the commit: `git add -A`
    - `git status`
    - Commit the changes with `git commit -m "Enter commit message here"`
    - See history of commits: `git log`, `git log --stat`, `git log --patch`, `git log --oneline`
      - [More info here](https://git-scm.com/docs/git-log)
    - Set an alias for our favorite way to view history:  `git config --global alias.lol "log --oneline --graph --decorate --all"`
    - `git lol`
  - Practice the Two Stage Commit on another branch (Note: We are only commiting to Master as an example, it is considered bad practice in common workflows.)
    - Checkout to master: `git checkout master`
    - Create a file: `touch file1.md`
    - See `git status`
    - Add the file to staging: `git add file1.md`
    - git status
    - `git commit -m "adding blank file 1"`
    - `git lol`
  - Merge the branch
    - `git merge update-readme`
    - `git lol`

#### Getting ready for next hour:

Please comment on [this issue](https://github.com/githubteacher/essentials-aug/issues/1) so you will have collaborator access for our next section of work. ✨

**Comment by koffisani** [comment]
Ypu mean `git log` or `git lol` ?

**Comment by brianamarie** [comment]
@koffisani In the instructions above, it's using an alias that's been set up ONLY in this version of notes - we haven't covered it yet in class. `git log` will work great. Nice catch! 😄

**Comment by NGenetzky** [comment]
@brianamarie At the end would you be willing to post the source markdown? I take my notes directly in markdown and would like to add your notes to them.

**Comment by brianamarie** [comment]
## Day 1: Wednesday, August 10

Section 2/3

#### Collaborating
- Copy the class repository locally
  - CD out of your current repository
  - Clone the repository: `git clone https://github.com/githubteacher/git-essentials-may-2016.git`
- Create a branch for your own work
  - `git branch your-user-name-hello-world`
  - `git checkout your-user-hello-world`
- Create a file in your preferred language, and fill it with a 'hello world' exercise
- Two stage commit
  - `git add .`
  - `git status`
  - `git commit -m 'creating helloworld'`
- Push your changes to the remote repository
  - `git push -u origin your-user-hello-world`
  - If this doesn't work, you may not be a collaborator. Comment [here](https://github.com/githubteacher/essentials-aug/issues/2) so we can add you.

#### More Collaborating
- Update your local repository
  - View all branches, even remote: `git branch --all`
  - Move to master: `git checkout master`
  - Fetch changes from remote: `git fetch`
  - Merge those changes into your own local repository: `git merge`
  - Combine those tasks with: `git pull`
- Let's fill out more of our own documents
  - Open your document within your own branch
  - Add details about what to do & where to eat
  - Save & close
  - See where we are with `git status`
  - Two stage commit (`git add .` & `git commit -m "commit message"`)
- Open a pull request on GitHub.com and follow the steps we used before

**Comment by brianamarie** [comment]
## Day 1: Wednesday, August 10

**Note: There are minor differences between these notes and the webinar video. However, the main content is the same.**

#### Practicing Open Source Workflows
- Create your own copy
- Go to the [Github Games](https://github.com/githubschool/github-games) repository
- `gh-pages` is the default branch for this repository, not `master` like yesterday
  - When `gh-pages` is the default branch, you can see the code as a GitHub Pages site. This class's link is [here](http://githubschool.github.io/github-games/)
-  Create a new repository
  - You are the owner, and the repository name can be anything. Ours is `github-games`.
  - Don't select any options, just click 'create repository'.
  - Go back to the original repository, [Github Games](https://github.com/githubschool/github-games) owned by 'GitHub School'
  - To clone this locally, copy the 'clone url'. Go to the command line and clone: `git clone <https-url-from-clipboard>`

#### Make our changes
- We need to change a link in the workflow.
- Create a branch locally and checkout to that branch: `git checkout -b readme-updates`
- See all branches: `git branch --all`
- Open the README.md file from the `readme-updates` branch.
- Update the link in line 5 to replace "githubschool" with your own username.
- Check the status: `git status`
- Two step commit:
  - `git add FILENAME` or `git add -A`, then `git status` to check
  - `git commit -m "Enter commit message"`
  - Check the log: `git log --oneline --graph --decorate --all`, or use the alias from yesterday, `git lol`

#### Merge our changes to `gh-pages` branch
- Check out to the branch that we are merging into: `git checkout gh-pages`
- See log: `git lol`
- Merge the `readme-update` branch: `git merge readme-updates`
- See what has merged: `git branch --merged`
- Delete the branch we just created and merged:  `git branch -d readme-updates`

#### Push our work to the remote repository
- See the configured remotes: `git remote -v`
  - The remotes listed do not allow us to push, so we need another option
- Add another remote that we will have permission to
  - Copy the URL from the repository you created on GitHub.com
  - `git remote add mygame <copied-URL>`
- Push up your changes to your repository: `git push -u mygame gh-pages`.
  - The `u` flag sets a relationship with the branch in the remote repository.
- Check your remotes: `git remote -v`.

### If you cloned the githubteacher/github-games repository, you can set your new upstream:

`git remote add teacher https://github.com/githubteacher/github-games.git` with your own information. 
[Notes on setting multiple remotes here](https://git-scm.com/book/en/v2/Git-Basics-Working-with-Remotes)

History log here:
<img width="653" alt="screen shot 2016-08-10 at 1 48 17 pm" src="https://cloud.githubusercontent.com/assets/9906718/17566477/24e2ef7a-5f01-11e6-82cd-ac6e0d19ea5e.png">

**Comment by githubteacher** [comment]
## Command Line History for Day 1

500  git --version
  501  git config --global user.name "Cynthia Rich"
  502  git config --global user.name
  503  git config --global --list
  505  git config --global user.email "crichID@github.com"
  506  git config --global core.autocrlf input
  507  git config --global push.default simple
  508  atom .
  509  cd documents/scratch
  510  git init my-repo
  511  cd my-repo
  512  ls -al
  513  tree .git
  514  clear
  515  ls
  516  echo "## Welcome to Class" >> README.md
  517  git status
  518  git add README.md
  519  git commit
  520  tree .git
  521  clear
  522  git log
  523  git branch
  524  git branch my-feature
  525  git branch
  526  git checkout my-feature
  527  touch file1.md
  528  git status
  529  git add file1.md
  530  git status
  531  git commit -m "adding file1 to my repo"
  532  ls
  533  git log
  534  git checkout master
  535  git log
  536  ls
  537  git merge my-feature
  538  ls
  539  git log
  540  git branch
  541  git branch --merged
  542  git branch -d my-feature
  543  git log
  551  cd scratch
  552  git clone https://github.com/githubteacher/essentials-aug.git
  553  cd essentials-aug
  554  git status
  555  ls -al
  556  git branch
  557  git branch --all
  558  git branch githubteacher-hello
  559  git checkout githubteacher-hello
  560  atom .
  561  git status
  562  git add .
  563  git status
  564  git commit -m "adding a basic helloworld file in markdown"
  565  git log
  566  git branch --all
  567  git push -u origin githubteacher-hello
  568  git branch --all
  577  git checkout master
  578  git pull
  579  git branch --all
  580  git checkout utcwebdev-hello
  581  git branch
  582  ls
  583  cat utcwebdev-hello.md
  584  git checkout etnolover-hello
  585  ls
  586  cat etnolover-hello.md
  587  git checkout master
  588  git diff master origin/mleacct-hello
  589  git log
  590  git log --stat
  591  git log --patch
  592  git log --oneline
  593  git log --oneline --graph
  594  git log --oneline --graph --decorate
  595  git branch --all
  596  git log --oneline --graph --decorate --all
  597  git log --oneline --graph --decorate --all
  598  git config --global alias.lol "log --oneline --graph --decorate --all"
  599  git lol
  600  git status
  601  git checkout master
  602  ls -al
  603  git pull
  604  ls -al
  605  git branch --all
  606  git pull --prune
  607  git branch --all
  608  git branch --merged
  609  git branch -d etnolover-hello githubteacher-hello utcwebdev-hello
  610  cd ..
  614  git clone https://github.com/githubschool/github-games.git
  615  cd github-games
  616  git lol
  617  git diff --color-words 7b5464c c5b2523
  618  git checkout stats-update
  619  git checkout gh-pages
  620  git merge stats-update
  621  git status
  622  atom inde.html
  623  git status
  624  git add inde.html
  625  git status
  626  git commit
  627  git lol
  628  git remote
  629  git remote -v
  630  git remote add teacher https://github.com/githubteacher/github-games.git
  631  git remote -v
  632  git branch --all
  633  git fetch teacher
  634  git branch --all
  635  git branch shape-colors origin/shape-colors
  636  git branch --all
  640  git remote show origin
  641  git remote show teacher
  642  clear
  643  git branch --all
  644  git checkout shape-colors
  645  git merge teacher/shape-colors
  646  atom inde.html
  647  git checkout gh-pages
  648  git merge shape-colors
  649  git lol
  650  git status
  651  atom inde.html
  652  git status
  653  git add inde.html
  654  git status
  655  git commit --no-edit
  656  git branch --all
  657  git remote remove teacher
  658  git branch --all
  659  git branch --merged
  660  git branch -d shape-colors stats-update
  661  git lol
  662  history

**Comment by brianamarie** [comment]
# Day 2: Thursday, August 11

Section 1/3

### Starting off with `git bisect`
- CD into the repository we were working on yesterday: `cd github-games` 
- `git lol` (set this with `git config --global alias.lol "log --oneline --graph --decorate --all"`)
-  Start the bisect: `git bisect start`, then run `git status`
- `git bisect bad <commit ID where things weren't working>`
- `git bisect good <commit ID where you knew everything was working>`
- `git status`
- `ls`
- `git bisect bad`
- `ls -al`
- `git bisect bad`, meaning that at this commit, the repository is still broken
- Everything worked at this point, so we type `git bisect good`. 
- Git Bisect helps you look for a commit that broke the build. 
- We get out of the bisect: `git bisect reset` 

#### New Feature
- Create a new branch and checkout to that branch: `git checkout -b slow-down`
- Open index.html. We are going to change the speed in the index.html file, line 78.
- On line 78, change the speed to be slower (or faster if you'd like!)
- Save the file and close the text editor.
- Make a new directory called images: `mkdir images`.
- Hunk the changes with a patch:
  - `git add -p`
  - `y`
  - `n`
  - `git status`
  - Confirm changes with `git diff`
  - `git commit -m "enter commit message"`
  - `git status`
  - `git diff --color-words HEAD`
  - `git add .`
  - `git commit --m "commit message"`
  - `git checkout gh-pages`
  - `git merge slow-down`
  - `git push`

#### Practice rewriting history
- CD back into your preferred directory to create a new repository
- Create a new repository locally: `git initializing practice-repo`
- CD into that repository: `cd practice-repo`
- Create a README: `touch README.md`
- Add the readme to the repository: `git add README.md`
- Commit the readme: `git commit -m "init the repository with a README"`
- We are going to use empty files to practice rewriting history
  - `for d in {1..6}; do touch file$d.md; git add file$d.md; git commit -m "adding file $d"; done`

**Comment by brianamarie** [comment]
## Day 2

#### Git Reset
- Find resource for `git reset` [here](https://services.github.com/kit/modules/CONT-CLI-19_Resetting-history.html)
- Be careful with `git reset` when pushing to a remote repository. Any time you push a commit, you should not use reset locally again. The commit ID will change, and that will alter their history in a possibly dangerous way.
- Three types of reset
  - `git reset --soft`
    - Commits will go into the staging area
  - `git reset --mixed`
    - Default behavior of `git reset`
    - Commits will go into the working directory
  - `git reset --hard`
    - Commits will be deleted

#### Git Reset
- Find resource for `git reset` [here](https://services.github.com/kit/modules/CONT-CLI-19_Resetting-history.html)
- Be careful with `git reset` when pushing to a remote repository. Any time you push a commit, you should not use reset locally again. The commit ID will change, and that will alter their history in a possibly dangerous way.
- Three types of reset
  - `git reset --soft`
    - Commits will go into the staging area
  - `git reset --mixed`
    - Default behavior of `git reset`
    - Commits will go into the working directory
  - `git reset --hard`
    - Commits will be deleted

#### Practice `git reset --soft`
- See history: `git lol`
- Go back two commits: `git reset --soft HEAD~2`
  - See history now: `git lol`
  - Check status: `git status`
- Commit those changes: `git commit -m "adding files 3 and 4"`
  - Check status: `git status`
  - See history: `git lol`

#### Practice `git reset`/`git reset --mixed`
- Go back with `git reset <first-4-chars-of-commit-adding-file-2>`
  - Check status: `git status`
  - See history: `git lol`
- Re add those files
  -Re-add file 3: `git add *3*`
  -Re-commit file 3: `git commit -m "re-adding file 3"`
  -Re-add file 4: `git add *4*`
  -Re-commit file 4: `git commit -m "re-adding file 4"`
- Notice that the Commit ID is different than the first time those files were committed

#### Practice `git reset --hard`
- `git reset --hard <first-4-char-of-initalizing-repository>`
- This is a destructive command!
  - However, if you are _only_ working locally, you can rescue commits using `git reflog`.
  - `git reflog` does not stick around forever!
  - It only lasts for 90 days for a reachable commit.
  - Unreachable commits only last for 30 days.
  - These changes can be made in Git's configurations
  - The reflog is only local - nobody else with a copy of the repository will have access to your reflog.

#### Using Reflog and Cherry-pick
- `git reflog` to find that commit where we added file 2
- `git cherry-pick <first-4-chars-of-commit>`
- See history: `git lol`

#### Great Resource
- [Git Cheat Sheet](https://services.github.com/kit/downloads/github-git-cheat-sheet.pdf)
- [ProGit](https://git-scm.com/book/en/v2) by Scott Chacon and Ben Straub
- [Git Documentation](https://git-scm.com/docs/git)
